### ISSUE TITLE
Request Sample to how create a Pad like application_output 

### ISSUE THREAD

**Issue by JoacimWall** [mrward/vsmac-extensibility-samples#1]
Hi 
As there is no documentation on how to develop extensions for vs2022 for mac. maybe you know how to do it.
I have no success.
I just wont a Pad to write logs from my extension to.

//Thanks Joacim

**Comment by mrward** [comment]
The template creator addin has a pad that displays output.

https://github.com/mrward/monodevelop-template-creator-addin/blob/main/src/MonoDevelop.TemplateCreator/MonoDevelop.Templating.Gui/TemplatingOutputPad.cs

If the pad does not need to remain alive for the entire IDE session, and could be displayed in response to some action, you can use an output progress monitor. This is what is used for the NuGet Package Console window, and other windows, such as the Tool output window. Here you write the log messages to the progress monitor.

Output progress monitor/pad - https://github.com/mono/monodevelop/blob/ca84d5037376cea6efc342e101d72966589ef4ed/main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementProgressMonitorFactory.cs#L75

Tool output progress monitor/pad - https://github.com/mono/monodevelop/blob/ca84d5037376cea6efc342e101d72966589ef4ed/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/CustomToolService.cs#L125

**Comment by JoacimWall** [comment]
Thanks!!
Works perfect. 

//Regards Joacim
